version: 2
project_name: gitmorph

# Builds configuration
builds:
  # macOS universal: build two architectures first
  - id: darwin_universal_arm64
    binary: gitmorph_arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0

  - id: darwin_universal_amd64
    binary: gitmorph_amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  # Linux builds
  - id: linux_amd64
    binary: gitmorph
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  - id: linux_arm64
    binary: gitmorph
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0

# Archives: include only the binary at root
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}"
    files:
      - gitmorph

# Homebrew tap
brews:
  - name: gitmorph
    homepage: "https://github.com/abhigyan-mohanta/gitmorph"
    description: "Switch between multiple Git profiles effortlessly 🚀"
    license: "MIT"
    repository:
      owner: abhigyan-mohanta
      name: homebrew-gitmorph
    commit_author:
      name: abhigyan-mohanta
      email: underthunder02@gmail.com
    install: "bin.install 'gitmorph'"

# Release configuration
release:
  github:
    owner: abhigyan-mohanta
    name: gitmorph
  prerelease: auto

# Changelog
changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Before hooks: create universal binary for macOS
before:
  hooks:
    - go mod tidy
    - |
      # Create universal macOS binary
      if [[ "$GOOS" == "darwin" ]]; then
        lipo -create \
          dist/darwin_universal_arm64_darwin_arm64_v8.0/gitmorph_arm64 \
          dist/darwin_universal_amd64_darwin_amd64_v1/gitmorph_amd64 \
          -output dist/gitmorph
      fi
