version: 2
project_name: gitmorph

builds:
  - id: gitmorph_linux_amd64
    main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

  - id: gitmorph_linux_arm64
    main: ./main.go
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

  - id: gitmorph_darwin_amd64
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

  - id: gitmorph_darwin_arm64
    main: ./main.go
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

# Universal macOS binary
universal_binaries:
  - id: gitmorph
    name_template: "{{.ProjectName}}_{{.Version}}"
    ids:
      - gitmorph_darwin_amd64
      - gitmorph_darwin_arm64
    replace: true

# Archive both Linux builds and the universal Darwin binary
archives:
  - id: linux_archives
    builds:
      - gitmorph_linux_amd64
      - gitmorph_linux_arm64
    format: tar.gz
    
  - id: darwin_archive
    builds:
      - gitmorph  # This references the universal binary ID
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_darwin_all"

homebrew_casks:
  - name: gitmorph
    homepage: "https://github.com/abhigyan-mohanta/gitmorph"
    repository:
      owner: abhigyan-mohanta
      name: homebrew-tap
    # Reference the archived universal binary
    ids:
      - darwin_archive
    binary: gitmorph
