name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout full history for tags
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set up Go (needed for GoReleaser)
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 3️⃣ Calculate next version automatically
      - name: Calculate next version
        id: next_version
        shell: bash
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          while true; do
            PATCH=$((PATCH + 1))
            if [ $PATCH -gt 9 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
              if [ $MINOR -gt 9 ]; then
                MINOR=0
                MAJOR=$((MAJOR + 1))
              fi
            fi
            NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"
            # Check if tag exists
            if ! git rev-parse "$NEXT_VERSION" >/dev/null 2>&1; then
              break
            fi
          done

          echo "Next version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      # 4️⃣ Configure git to use token for pushing tags
      - name: Configure Git for token
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PUBLISHER_TOKEN }}@github.com/${{ github.repository }}.git

      # 5️⃣ Tag & push
      - name: Create and push tag
        run: |
          git tag ${{ steps.next_version.outputs.next_version }}
          git push origin ${{ steps.next_version.outputs.next_version }}

      # 6️⃣ Install GoReleaser
      - name: Install GoReleaser
        run: curl -sL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | bash

      # 7️⃣ Run GoReleaser
      - name: Release with GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        run: goreleaser release --clean
