name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Auto Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed to fetch all tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install GoReleaser
        run: |
          curl -sL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | bash

      - name: Calculate next version
        id: next_version
        run: |
          LAST_TAG=$(git fetch --tags && git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          while true; do
            PATCH=$((PATCH + 1))
            if [ $PATCH -gt 9 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
              if [ $MINOR -gt 9 ]; then
                MINOR=0
                MAJOR=$((MAJOR + 1))
              fi
            fi

            NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"
            if ! git rev-parse "$NEXT_VERSION" >/dev/null 2>&1; then
              break
            fi
          done

          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION
          echo "Next version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      - name: Configure Git for GoReleaser
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        run: |
          goreleaser release --clean --rm-dist
