name: Auto Release

on:
  push:
    branches:
      - main

# Add permissions for the workflow
permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout full history for tags
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Set up Go (needed for GoReleaser)
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # 3️⃣ Calculate next version automatically
      - name: Calculate next version
        id: next_version
        shell: bash
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          VERSION=${LAST_TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          while true; do
            PATCH=$((PATCH + 1))
            if [ $PATCH -gt 9 ]; then
              PATCH=0
              MINOR=$((MINOR + 1))
              if [ $MINOR -gt 9 ]; then
                MINOR=0
                MAJOR=$((MAJOR + 1))
              fi
            fi
            NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"
            # Check if tag exists
            if ! git rev-parse "$NEXT_VERSION" >/dev/null 2>&1; then
              break
            fi
          done

          echo "Next version: $NEXT_VERSION"
          echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT

      # 4️⃣ Configure git to use GITHUB_TOKEN
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 5️⃣ Tag & push using GITHUB_TOKEN
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.next_version.outputs.next_version }}
          git push origin ${{ steps.next_version.outputs.next_version }}

      # 6️⃣ Run GoReleaser
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
